"""initial schema

Revision ID: 02a4d33f7450
Revises: 
Create Date: 2026-04-01 12:44:30.701408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a4d33f7450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('comp_est', sa.String(length=100), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ats_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('filled_fields_json', sa.JSON(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_model', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_external_id'), 'applications', ['external_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('location_current', sa.String(length=255), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('current_ctc', sa.String(length=50), nullable=True),
    sa.Column('expected_ctc', sa.String(length=50), nullable=True),
    sa.Column('expected_ctc_min_lpa', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('graduation_month_year', sa.String(length=20), nullable=True),
    sa.Column('graduation_year', sa.String(length=10), nullable=True),
    sa.Column('cgpa', sa.String(length=10), nullable=True),
    sa.Column('total_experience', sa.String(length=255), nullable=True),
    sa.Column('work_authorization', sa.String(length=255), nullable=True),
    sa.Column('willing_to_relocate', sa.String(length=255), nullable=True),
    sa.Column('willing_to_travel', sa.String(length=10), nullable=True),
    sa.Column('sponsorship_required', sa.String(length=10), nullable=True),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('eeo_json', sa.JSON(), nullable=True),
    sa.Column('preferred_roles', sa.Text(), nullable=True),
    sa.Column('target_locations', sa.Text(), nullable=True),
    sa.Column('avoid_roles', sa.Text(), nullable=True),
    sa.Column('avoid_companies', sa.Text(), nullable=True),
    sa.Column('minimum_compensation', sa.Text(), nullable=True),
    sa.Column('must_have_preferences', sa.Text(), nullable=True),
    sa.Column('deal_breakers', sa.Text(), nullable=True),
    sa.Column('candidate_summary', sa.Text(), nullable=True),
    sa.Column('experience_highlights', sa.Text(), nullable=True),
    sa.Column('short_answers_json', sa.JSON(), nullable=True),
    sa.Column('blacklist_companies', sa.JSON(), nullable=True),
    sa.Column('blacklist_keywords', sa.JSON(), nullable=True),
    sa.Column('min_comp_lpa', sa.Integer(), nullable=False),
    sa.Column('target_comp_lpa', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_external_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
